name: Daily Pincode Check
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 00:00 UTC (5:30 AM IST)
  workflow_dispatch:  # Lets you run it manually

jobs:
  test-pincode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Run pincode test
        run: python pincode_checker.py
      
      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Pincode Checker Failed!"
          body: "The daily pincode checker test failed. Check logs: https://github.com/your-username/shopify-pincode-monitor/actions"
          to: apurv.auburn@gmail.com  # Replace with your email
          from: GitHub Actions
